services:

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-data:/data/db

  backend:
    image: gowtham755/mean-backend
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017/tasks
    depends_on:
      - mongo

  frontend:
    image: gowtham755/mean-frontend
    restart: always
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

volumes:
  mongo-data:
